[server]
    port = ":8080"

[database]
    connection_string = "mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false"
    database_name = "test"
[jwt]
    Key = "qwerty"

[logs]
    log_level = "info"

